DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS school_fav CASCADE;
DROP TABLE IF EXISTS major_fav CASCADE;
DROP TABLE IF EXISTS major_rec CASCADE;
DROP TABLE IF EXISTS school_rec CASCADE;
DROP TABLE IF EXISTS chatlog CASCADE;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    google_auth TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE major_rec(
    id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	major_id INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_major FOREIGN KEY(major_id) REFERENCES majors(id)
);

CREATE TABLE school_rec(
    id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	school_id INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_school FOREIGN KEY(school_id) REFERENCES schools(id)
);

CREATE TABLE chatlog(
    id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
    chat_text TEXT,
    isUser BOOLEAN NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE major_fav(
    id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	major_id INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_major FOREIGN KEY(major_id) REFERENCES majors(id)
);

CREATE TABLE school_fav(
    id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	school_id INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_school FOREIGN KEY(school_id) REFERENCES schools(id)
);